name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-22.04


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3 \
            python3-pip \
            python3-venv \
            openjdk-17-jdk \
            unzip \
            zip \
            git \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libssl-dev \
            zlib1g-dev \
            autoconf \
            automake \
            libtool \
            pkg-config

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install Buildozer
        run: |
          source venv/bin/activate
          pip install buildozer cython==0.29.36

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flappybird-apk
          path: bin/*.apk


